### ISSUE TITLE
Support many workflows files

### ISSUE THREAD

**Issue by bieganowski** [geosolutions-it/django-wfe#9]
Implement a support for multiple files with workflows definitions

**Comment by giohappy** [comment]
@bieganowski does this depend on django-wfe itself? I mean, the workflow definitions are provided by the hosting project and django-wfe shouldn't be aware of where and how many they are.
Can you please clarify this point and hwo the current implementation affect this?

**Comment by bieganowski** [comment]
django-wfe needs to be aware of the files defining Workflows, since the dynamic, automated update of the database with the user defined workflows is already in place in the basic form (so users don't have to update the database manually - manual approach was way to error prone, just a typo caused quite a lot of errors) :)

Currently there is only one file supported:
![image](https://user-images.githubusercontent.com/57660086/81144916-6106c280-8f75-11ea-90a7-2c919ad5c7cf.png)

This task aims to provide support to the multiple files, e.g. spread across multiple apps (something similar to a middleware list).

**Comment by giohappy** [comment]
Ok, as agreed of course we need to be able to configure multiple workflows, but we will simplify the settings by removing the STEPS and DECISIONS modules declarations.
